name: botoneira
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^4.2.0
  mobx: ^2.0.3
  flutter_mobx: ^2.0.1
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
  file_picker: ^4.1.3
  audioplayers: ^0.20.1
  permission_handler: ^6.1.3 
  splashscreen: ^1.3.5
  fluttertoast: ^8.0.8
  nine_grid_view: ^2.0.0   
  rect_getter: ^1.0.0
  dartz: ^0.10.0
  uuid: ^3.0.5

dev_dependencies:
  mockito: ^5.0.16
  modular_test: ^1.0.1+1
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.2
  build_runner: ^2.1.5
  change_app_package_name: ^0.1.2
  flutter_launcher_icons: ^0.9.2
 
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
